#ifndef CPOSDETAPP_H
#define CPOSDETAPP_H

#include "AEEStdDef.h"
#include "AEEInterface.h"

//WARNING: This classID was locally generated by the wizard 8/7/2012
//For commercializing this module, please get a valid ClassID.
#define AEECLSID_CPOSDETAPP 0x00C5188D

#define SPD_CONFIG_FILE             "config.txt"
#define SPD_CONFIG_OPT_STRING       "GPS_OPTIMIZATION_MODE = "
#define SPD_CONFIG_QOS_STRING       "GPS_QOS = "
#define SPD_CONFIG_SVR_TYPE_STRING  "GPS_SERVER_TYPE = "
#define SPD_CONFIG_SVR_IP_STRING    "GPS_SERVER_IP = "
#define SPD_CONFIG_SVR_PORT_STRING  "GPS_SERVER_PORT = "
#define SPD_QOS_DEFAULT       127

#define GPSCBACK_DOGTIMER 30000 // milliseconds
#define GPSCBACK_INTERVAL 5     // seconds

#endif /* #ifndef CPOSDETAPP_H */
