#ifndef CPOSDETAPP_H
#define CPOSDETAPP_H

#include "AEEStdDef.h"
#include "AEEInterface.h"

//WARNING: This classID was locally generated by the wizard 8/7/2012
//For commercializing this module, please get a valid ClassID.
#define AEECLSID_CPOSDETAPP 0x00C5188D

#define SPD_CONFIG_FILE             "config.txt"
#define SPD_CONFIG_OPT_STRING       "GPS_OPTIMIZATION_MODE = "
#define SPD_CONFIG_QOS_STRING       "GPS_QOS = "
#define SPD_CONFIG_SVR_TYPE_STRING  "GPS_SERVER_TYPE = "
#define SPD_CONFIG_SVR_IP_STRING    "GPS_SERVER_IP = "
#define SPD_CONFIG_SVR_PORT_STRING  "GPS_SERVER_PORT = "
#define SPD_QOS_DEFAULT       127

#define GPSCBACK_INTERVAL     0    // seconds

#define REPORT_STR_BUF_SIZE   256

#ifdef _DEBUG
#define SPD_LOG_FILE                "log.txt"
#endif

// Only for test
#define TERMINAL_ID     "13800000000"
#define MILEAGE         "8888.22"
#define TERMINAL_STATUS "0061006"
#define TERMINAL_ALARM  "0006007"
#define SATELLITE_NUM   "6"
#define POLICEMAN_ID    ""

// define port number and IP address of the server
#define SERVER_PORT   0x1212
#define SERVER_ADDR   "129.46.229.214"

// define message length
#define BUFFER_SIZE   REPORT_STR_BUF_SIZE

#endif /* #ifndef CPOSDETAPP_H */
